### ISSUE TITLE
IE10 click on arrow

### ISSUE THREAD

**Issue by IschaGast** [filamentgroup/select-css#10]
When clicking the arrow in IE10 nothing happens, clicking anywhere else it just works fine.

**Comment by akkis** [comment]
Yes, because of pointer-events: none CSS rule.

By reading this http://caniuse.com/#feat=pointer-events you see that IE10 is not supported.

**Comment by zachleat** [comment]
This is a good report. I’m not sure there’s a CSS-only way to fix this, however—for now it’ll just be a limitation of the plugin.
