### ISSUE TITLE
Cross-browser compatibility (OSX/Safari)

### ISSUE THREAD

**Issue by progcode** [filamentgroup/select-css#15]
The default select form elements are broken in Safari (8/9 OSX Yosemite / El Capitan).

![filament_select](https://cloud.githubusercontent.com/assets/5430762/14632996/cf4e7086-061b-11e6-8ee9-6d9ed18a55fa.png)

**Comment by zachleat** [comment]
Hm? The demo page is behaving fine for me on Safari 9.0.3/OS X El Capitan

Please open with additional information or a more specific test case, maybe a screenshot that includes devtools inspector? Are there errors in your console?
