### ISSUE TITLE
Disable Styling

### ISSUE THREAD

**Issue by nicktobolski** [filamentgroup/select-css#19]
What's an elegant way to handle the styling of the disabled select element? I could add `disabled="disabled"` to the select element itself but then I'd need to add a class to the wrapper div as well. 

Thoughts?

**Comment by ahmadalfy** [comment]
I think the only way is to add an identifier to the wrapper. With the attribute you cannot do much except for maybe setting opacity to the disabled select
```
select[disabled] {
    opacity: 0.5;
}
```

And it will look like this:

![image](https://cloud.githubusercontent.com/assets/87611/21296748/656915b6-c57b-11e6-9134-c17c4ae39f7e.png)

Sadly that doesn't give any kind of control over how the rest of the element will look like the caret and the background. That's a significant drawback unless you don't mind changing the markup.

**Comment by zachleat** [comment]
Yeah, unfortunately not much we can do here @nicktobolski. Hooking into the `disabled` attribute (as @ahmadalfy mentioned), won’t give you much help on the parent element. This is likely outside of the scope of this CSS only plugin.

We do have a JS wrapper component though! Have you looked at that? https://github.com/filamentgroup/select/
