### ISSUE TITLE
Explicit z-index on arrow unnecessary?

### ISSUE THREAD

**Issue by robinwhittleton** [filamentgroup/select-css#21]
The arrow was overlaying a fixed element in my app [due to a `z-index:2` in the styles](https://github.com/filamentgroup/select-css/blob/883470492e7dd678409618b782b5f9dcab96f4f8/src/select-css.css#L33). I’ve undone this locally with `z-index:auto` but I’m not sure why it’s in there from the start. I did a bit of blame spelunking and it [was in there in the initial drop of code](https://github.com/filamentgroup/select-css/commit/524166e80f09719811505f5fbe8c96560379cef8#diff-692e2c67c40d272d0275e0f4ab00e983R46). Is this still necessary?

**Comment by scottjehl** [comment]
No longer using this CSS so we're good! Thanks
