### ISSUE TITLE
Unwanted border around <select>

### ISSUE THREAD

**Issue by maciej-gurban** [filamentgroup/select-css#22]
Correct me if I'm mistaken, but it looks like an unnecessary border appears around `<select>` element when it's being clicked. The border doesn't disappear until `<select>` loses its focus. Here's a [fiddle](https://jsfiddle.net/maciejgurban/p0vk3s2w/) demonstrating the issue and a possible fix.

<img width="607" alt="screen shot 2017-12-10 at 13 50 16" src="https://user-images.githubusercontent.com/3663640/33804607-1d203cf4-ddb1-11e7-900a-eeb0bdf39d04.png">

Tested on latest Chrome and Firefox.

In Firefox, there's additionally another border around the `<select>` element, that doesn't seem to go away even when removing outline and border. On the picture, the one visible only in FF is the inner one.

<img width="120" alt="screen shot 2017-12-10 at 13 48 50" src="https://user-images.githubusercontent.com/3663640/33804594-ea4b5746-ddb0-11e7-879d-fb25fc8d586b.png">

**Comment by scottjehl** [comment]
This is I think fixed in master now. Please let me know if not!
