### ISSUE TITLE
Hiding select area in IE11 

### ISSUE THREAD

**Issue by RinatValiullov** [filamentgroup/select-css#39]
I have some annoying issue in IE 11.0.9600.19230 (Windows 7 Ultimate)

When I choose some option (click on it) the select hides itself and the pack of options overlaps it.

![IE11 Issue](https://user-images.githubusercontent.com/9755333/50763781-9bcded00-1292-11e9-8de7-cbb45ea9ba8f.png)

**Comment by toddparker** [comment]
I’m pretty sure this is just how Windows handles placement and collision detection for select menus? Does it behave the same with a non-styled select?

**Comment by toddparker** [comment]
@RinatValiullov thanks for the detailed animations. What are the main issues you see? I see you seem to be pointing out:
- the edges of the focus style on the button behind the edges of the menu 
- the blue background highlighting the selected option while the select is focused

**Comment by RinatValiullov** [comment]
> @RinatValiullov thanks for the detailed animations. What are the main issues you see? I see you seem to be pointing out:
> 
> * the edges of the focus style on the button behind the edges of the menu
> * the blue background highlighting the selected option while the select is focused

The most first example as I noticed initially. Overlapping. I think it doesn't look good :thinking:

**Comment by equinusocio** [comment]
This is the default browsers implementation on various OS. Since Edge will switch to Chronium this year, i think this can be considered not a bug. This project doesn't handle the dropdown menu, just the select element (and its style)
