### ISSUE TITLE
Publish on npm, bower?

### ISSUE THREAD

**Issue by anselmh** [filamentgroup/select-css#6]
Wouldn’t it make sense to publish the package on npm and bower so one could fetch it that way?

**Comment by Undistraction** [comment]
Yes it would. Please add to npm (and bower).

**Comment by AntonTrollback** [comment]
Have a look at this. Available on npm https://github.com/AntonTrollback/select

**Comment by zachleat** [comment]
This has been on npm for awhile at https://www.npmjs.com/package/fg-select-css

I don’t think we’ll do bower—thanks!
