### ISSUE TITLE
Readability issue with dark backgrounds in Firefox

### ISSUE THREAD

**Issue by brendanfalkowski** [filamentgroup/select-css#7]
Noting an issue I ran into building a JS-driven `select` replacement and testing this technique as an alternative (95% there).

Firefox uses the `background` CSS property for the `select` button and the menu which appears under interaction. This approach removes the background on `select` inputs:

```
.custom-select select {
    background: none;
}
```

This allows the input to be invisible and users see the `.custom-select` wrapper's styling. But this makes Firefox (taxingly) fallback to using the `body` background for the menu options background. Example:

![firefox-select-css-dark-background](https://cloud.githubusercontent.com/assets/214924/5190677/f62d7894-74b5-11e4-9b33-e4802db9affd.png)

I haven't found a fix other than don't use this technique on dark sites. In my JS-approach the `select` has `opacity:0; background:#FFF;` which forces Firefox to use a readable background, but this isn't possible here because the technique must render the `select`'s text visibly.

**Comment by brendanfalkowski** [comment]
After lots of frustration with my JS-driven select replacements, I'm back to CSS. Was pleasantly surprised to see fresh updates — but the background issue remains in Firefox. I think I found a fix.

## Assumption

Originally I thought Firefox took the `<option>` list background from the `<body>` but that's not entirely true. Tried putting a green wrapper DIV around the content and Firefox inherited that. Hmm...

![screen shot 2016-03-03 at 4 10 32 am](https://cloud.githubusercontent.com/assets/214924/13489606/fc321ea4-e0f5-11e5-93d0-9614dc30ae9b.png)

Then I tried putting a background-colored wrapper just around the `.custom-select` itself. That worked too, but you get some edge spill.

![screen shot 2016-03-03 at 4 16 19 am](https://cloud.githubusercontent.com/assets/214924/13489745/bdd7579a-e0f6-11e5-9d71-5e0135d2c34d.png)

So then I looked at the lone `.custom-select` wrapper itself.

## Firefox's behavior

What Firefox does with `select { appearance: none; }` is look behind the `select` to find the background color of its parent element (I think). This is applied as the <option> background which is normally not styleable at all in browsers.

The `.custom-select` (via `.button` inheritance in the demo) has a linear gradient with transparent as a solid-color fallback. Firefox won't apply a gradient to the `<option>`, and ignores "transparent" heading up the parent element until it finds a solid background color. The first parent that has one is applied as the `option` background.

```
.custom-select {
    background: transparent linear-gradient(to bottom, #FFF 0%, #E5E5E5 100%) repeat scroll 0% 0%;
}

.custom-select--firefox-proof {
    background: #FFF linear-gradient(to bottom, #FFF 0%, #E5E5E5 100%) repeat scroll 0% 0%;
}
```

If you change `transparent` to solid `#FFF` then Firefox will render the `<option>` readably — even if the `<body>` behind it is dark.

## Fixed

![screen shot 2016-03-03 at 4 10 17 am](https://cloud.githubusercontent.com/assets/214924/13489595/ebe92c40-e0f5-11e5-8613-bdd1b26e8d64.png)

Tested in current Firefox, Chrome, Safari, Opera, and IE10 (don't have other IEs handy). Specifying the solid fallback to linear-gradient seems to have no effect since other browsers don't behave like Firefox does for `<option>`. IE10 shows some slight border-radius color bleed, but that's normal.

Only consideration might be using not alpha values in the gradient since the solid will show through, but that's an easy fix with a solid-to-solid gradient.

I can make a PR tomorrow. I don't have a huge device suite to test though.

**Comment by brendanfalkowski** [comment]
Wasted an hour trying to figure out how to update my fork with the prior not-accepted PR, so I could apply updates and submit a new PR. Totally stumped. Going to delete my fork and start over. Don't know what that does to the old PR (I guess it disappears?).

**Comment by toddparker** [comment]
@brendanfalkowski - Sorry for the late reply, but if you wanted to put together a PR that would be great. Since this is mostly an issue for dark backgrounds, it might make sense to keep the core example transparent but offer this as a dark example with a note about why it needs to be done this way.

**Comment by brendanfalkowski** [comment]
@toddparker Sorry if I did this in the wrong branch, but I setup a PR here that adds an example on dark backgrounds to the demo: https://github.com/filamentgroup/select-css/pull/14
