### ISSUE TITLE
Don't set max-width on <select>

### ISSUE THREAD

**Issue by brendanfalkowski** [filamentgroup/select-css#9]
Just a heads-up:

If `select { max-width:100%; }` is defined, then Firefox will render its native dropdown button negating the `calc()` technique to hide it.

**Comment by zachleat** [comment]
Hmm, I’m not sure what you’re saying here. Do you think we should add something to the readme warning about this?

**Comment by brendanfalkowski** [comment]
Re-tested this and it's not an issue anymore in Firefox. Firefox updates or this module's change to @supports must have fixed it.

The `<select>` will render smaller than the visual wrapper, but that's expected. No issue with the arrow/button re-appearing.

Marking closed.
